### ISSUE TITLE
Services need to be refreshed to pick up changes in the bucket

### ISSUE THREAD

**Issue by katrinamariehh** [votinginfoproject/nginx-s3-auth#2]
@tie-rack @cap10morgan Sean and I were working on a ticket to deploy a new version of hidden at Maria's request--we were able to track down the bucket we needed to update and get the file in place but needed to restart the `nginx-s3-auth` services to see the changes.  Is this an update I can go ahead and make to the readme on this repo for future reference or is there something that we missed about getting changes deployed properly?

**Comment by tie-rack** [comment]
I _think_ that maybe redeploying isn't necessary. I believe [this line](https://github.com/votinginfoproject/nginx-s3-auth/blob/c6eda42a46a4c5e4a9de45f85feaa82172157fb1/nginx.conf#L30) says that the cache only lasts for 10 minutes. So changes in the bucket will be picked up with some delay.

Unless somehow the `download-bucket-and-serve-static` branch of this project is what's being deployed instead.

**Comment by katrinamariehh** [comment]
Oooh good call--I'll check how hidden.votinginfoproject.org is deployed and see if it's more how it's deployed rather than something to be noted on this repo

**Comment by katrinamariehh** [comment]
Yep, you were right @tie-rack, I'll close this issue.
